---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
  labels:
    app: prometheus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: prom
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - nodePort: 32409
    port: 9090
    targetPort: 9090

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: myprom
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: manglam240/prometheus:latest
        imagePullPolicy: IfNotPresent
        name: prom-os
        ports:
        - containerPort: 9090 
        volumeMounts:
        - name: prom-volume
          mountPath: "/metrics"
      volumes:
      - name: prom-volume
        persistentVolumeClaim:
          claimName: prom-pvc
